openapi: 3.0.0
info:
  title: onlineSub
  version: 1.0.0
  description: 'REST API service onlineSub'
servers:
  - url: http://0.0.0.0:8080
paths:
  /subscriptions:
    post:
      summary: create sub
      tags: [subscriptions]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionInput'
      responses:
        '201':
          description: Подписка создана
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                example:
                  id: "498b8443-b1d2-4e90-a9b1-7c414b9d3cab"
        '400':
          description: Ошибка в запросе
    get:
      summary: get list
      tags: [subscriptions]
      responses:
        '200':
          description: Список подписок
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'

  /subscriptions/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: get sub {id}
      tags: [subscriptions]
      responses:
        '200':
          description: Подписка найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
              example:
                id: "498b8443-b1d2-4e90-a9b1-7c414b9d3cab"
                service_name: "Yandex Plus"
                price: 500
                start_date: "2025-07-01T00:00:00Z"
                end_date:
                  Time: "0001-01-01T00:00:00Z"
                  Valid: false
                created_at: "2025-09-22T15:17:35.111358Z"
                updated_at: "2025-09-22T15:17:35.111358Z"
                user_id: "60601fee-2bf1-4721-ae6f-7636e79a0cba"
        '404':
          description: Подписка не найдена
    put:
      summary: put sub {id}
      tags: [subscriptions]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionInput'
      responses:
        '200':
          description: Подписка обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Ошибка в запросе
        '404':
          description: Подписка не найдена
    delete:
      summary: del sub {id}
      tags: [subscriptions]
      responses:
        '204':
          description: Подписка удалена
        '404':
          description: Подписка не найдена

  /subscriptions/aggregate:
    get:
      summary: get/agregate summary
      tags: [subscriptions]
      parameters:
        - name: from
          in: query
          required: false
          schema:
            type: string
            example: 01-2000
        - name: to
          in: query
          required: false
          schema:
            type: string
            example: 12-2026
        - name: user_id
          in: query
          required: false
          schema:
            type: string
            format: uuid
        - name: service_name
          in: query
          required: false
          schema:
            type: string
            example: Yandex Plus
      responses:
        '200':
          description: Общая сумма подписок
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                example:
                  total: 16200

components:
  schemas:
    Subscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
        service_name:
          type: string
        price:
          type: integer
        user_id:
          type: string
          format: uuid
        start_date:
          type: string
        end_date:
          type: object
          properties:
            Time:
              type: string
            Valid:
              type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    SubscriptionInput:
      type: object
      properties:
        service_name:
          type: string
        price:
          type: integer
        user_id:
          type: string
          format: uuid
        start_date:
          type: string

